language: node_js
node_js:
  - "7"
before_install: echo "Preparing build"
script: pushd todo && npm install && npm run build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
